---
dependencies:
  - python >= 3.7

    # for testing
  - pylint==2.4.4
  - flake8==3.7.9
  - flake8-colors==0.1.6
  - flake8-quotes==2.1.1
  - flake8-blind-except==0.1.1
  - flake8-pep3101==1.3.0
  - flake8-comprehensions==3.2.2
  - flake8-mutable==1.2.0

  - pip
  - pip:
    - bs4==0.0.1
    - aiohttp-apispec==2.2.0
    - aiohttp-cache==2.0.0
    - cachetools==4.0.0
